language: python
matrix:
    include:
        - python: 3.8
          dist: bionic
        - python: 3.8
          arch:   arm64
          dist: bionic
before_install:
    -  python -m pip install "pip<22"
    -  python -m pip install --upgrade setuptools wheel
install:
    -  pip install -r requirements/ci.txt
    -  python -m pip install --upgrade pip
    -  pip install redis-py-cluster
script:
    -  py.test -m "not integration" --cov-report=xml --cov-branch --max-runs=3
